version: '2'
services:
  app:
    container_name: storage_metrics
    image: ikewai/storage_metrics:latest
    environment:
      - IKE_SERVER=
      - IKE_TOKEN=
      - METRICS_UUID=
    volumes:
      - type: volume
       source: /mnt/netapp/ikewai
       target: /mnt/netapp/ikewai
       volume:
        read_only: true
      - 
    command: bash