version: '3.1'
services:
  app:
    container_name: storage_metrics
    image: ikewai/storage_metrics:latest
    environment:
      - IKE_SERVER=
      - IKE_TOKEN=
      - METRICS_UUID=8750519299985248746-242ac1110-0001-012
    volumes:
      - "/mnt/netapp/ikewai:/mnt/netapp/ikewai:ro"
    command: bash